[package]
name = "yosai_libauthz"
version = "0.1.0"
authors = ["Darin Gordon <dkcdkg@gmail.com>"]


[dependencies]
libc = "0.2.20"
authz = "0.1.5"


[lib]
name = "yosai_libauthz"
crate-type = ["cdylib"]
